name: 'Social Icon build'

on:
  workflow_dispatch:
  schedule:
    - cron: '* */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
      - name: install
        run: npm install
      - name: Update README.md
	run: |
	    npm run build

