name: 'Social Icon build'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
      - name: install
        run: yarn install
        
      - name: Build
        run: yarn run build

